// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: {
    About: [
      'about/getting-started',
      'about/namepaths',
      'about/commandline',
      'about/configuring-jsdoc',
      'about/configuring-default-template',
      'about/block-inline-tags',
      'about/plugins',
      'about/plugins-markdown',
      'about/tutorials',
      'about/including-package',
      'about/including-readme',
      'about/license-jsdoc3',
    ],
    'How to': [
      'howto/es2015-classes',
      'howto/es2015-modules',
      'howto/commonjs-modules',
      'howto/amd-modules',
    ],
    Tags: [
      'tags/abstract',
      'tags/access',
      'tags/alias',
      'tags/async',
      'tags/augments',
      'tags/author',
      'tags/borrows',
      'tags/callback',
      'tags/class',
      'tags/classdesc',
      'tags/constant',
      'tags/constructs',
      'tags/copyright',
      'tags/default',
      'tags/deprecated',
      'tags/description',
      'tags/enum',
      'tags/event',
      'tags/example',
      'tags/exports',
      'tags/external',
      'tags/file',
      'tags/fires',
      'tags/function',
      'tags/generator',
      'tags/global',
      'tags/hideconstructor',
      'tags/ignore',
      'tags/implements',
      'tags/inheritdoc',
      'tags/inline-link',
      'tags/inline-tutorial',
      'tags/inner',
      'tags/instance',
      'tags/interface',
      'tags/kind',
      'tags/lends',
      'tags/license',
      'tags/listens',
      'tags/member',
      'tags/memberof',
      'tags/mixes',
      'tags/mixin',
      'tags/module',
      'tags/name',
      'tags/namespace',
      'tags/override',
      'tags/package',
      'tags/param',
      'tags/private',
      'tags/property',
      'tags/protected',
      'tags/public',
      'tags/readonly',
      'tags/requires',
      'tags/returns',
      'tags/see',
      'tags/since',
      'tags/static',
      'tags/summary',
      'tags/this',
      'tags/throws',
      'tags/todo',
      'tags/tutorial',
      'tags/type',
      'tags/typedef',
      'tags/variation',
      'tags/version',
      'tags/yields',
    ],
  },
}

module.exports = sidebars
